### ISSUE TITLE
sesuaikan data assiten dengan data yang baru

### ISSUE THREAD

**Issue by izzuzantyaf** [izzuzantyaf/fisdascms#39]
### Todo
- [x] sesuaikan level dan gender asisten
- [x] hapus asisten yang udah ngga ngajar
- [x] tambahkan asisten yang baru
